package com.agilis.api.domain.notification;

public enum WebhookEventType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    NEGOTIATION_CREATED,
    NEGOTIATION_ACCEPTED,
    NEGOTIATION_REJECTED,
    NEGOTIATION_COUNTERED,
    MESSAGE_RECEIVED,
    REVIEW_CREATED,
    STORE_MEMBER_INVITED,
    STORE_MEMBER_REMOVED
}